//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaymsWPFBoiler.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConnectionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConnectionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaymsWPFBoiler.Data.Resources.ConnectionStrings", typeof(ConnectionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ADD COLUMN .
        /// </summary>
        internal static string DB_AddColumn {
            get {
                return ResourceManager.GetString("DB_AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE .
        /// </summary>
        internal static string DB_AlterTable {
            get {
                return ResourceManager.GetString("DB_AlterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string DB_CloseParenthesis {
            get {
                return ResourceManager.GetString("DB_CloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOB.
        /// </summary>
        internal static string DB_ColType_Blob {
            get {
                return ResourceManager.GetString("DB_ColType_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOLEAN.
        /// </summary>
        internal static string DB_ColType_Bool {
            get {
                return ResourceManager.GetString("DB_ColType_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME.
        /// </summary>
        internal static string DB_ColType_DateTime {
            get {
                return ResourceManager.GetString("DB_ColType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTEGER.
        /// </summary>
        internal static string DB_ColType_Int {
            get {
                return ResourceManager.GetString("DB_ColType_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARCHAR.
        /// </summary>
        internal static string DB_ColType_Varchar {
            get {
                return ResourceManager.GetString("DB_ColType_Varchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string DB_Comma {
            get {
                return ResourceManager.GetString("DB_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT NULL.
        /// </summary>
        internal static string DB_Constraint_NotNull {
            get {
                return ResourceManager.GetString("DB_Constraint_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY KEY.
        /// </summary>
        internal static string DB_Constraint_PrimaryKey {
            get {
                return ResourceManager.GetString("DB_Constraint_PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUE.
        /// </summary>
        internal static string DB_Constraint_Unique {
            get {
                return ResourceManager.GetString("DB_Constraint_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME NOT NULL DEFAULT(strftime(&apos;%Y-%m-%d %H:%M:%f&apos;, &apos;now&apos;)).
        /// </summary>
        internal static string DB_Constraints_DateTime {
            get {
                return ResourceManager.GetString("DB_Constraints_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATETIME DEFAULT(strftime(&apos;%Y-%m-%d %H:%M:%f&apos;, &apos;now&apos;)).
        /// </summary>
        internal static string DB_Constraints_DateTimeDefault {
            get {
                return ResourceManager.GetString("DB_Constraints_DateTimeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOB PRIMARY KEY UNIQUE NOT NULL.
        /// </summary>
        internal static string DB_Constraints_Guid {
            get {
                return ResourceManager.GetString("DB_Constraints_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL.
        /// </summary>
        internal static string DB_Constraints_Id {
            get {
                return ResourceManager.GetString("DB_Constraints_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT [Un-named].
        /// </summary>
        internal static string DB_Constraints_Name {
            get {
                return ResourceManager.GetString("DB_Constraints_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW IF EXISTS {0}; CREATE VIEW {0} AS .
        /// </summary>
        internal static string DB_CreateReplaceView {
            get {
                return ResourceManager.GetString("DB_CreateReplaceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE .
        /// </summary>
        internal static string DB_CreateTable {
            get {
                return ResourceManager.GetString("DB_CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER .
        /// </summary>
        internal static string DB_CreateTrigger {
            get {
                return ResourceManager.GetString("DB_CreateTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE UNIQUE INDEX .
        /// </summary>
        internal static string DB_CreateUniqueIndex {
            get {
                return ResourceManager.GetString("DB_CreateUniqueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW IF NOT EXISTS {0} AS .
        /// </summary>
        internal static string DB_CreateView {
            get {
                return ResourceManager.GetString("DB_CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON DELETE CASCADE.
        /// </summary>
        internal static string DB_DeleteAction_Cascade {
            get {
                return ResourceManager.GetString("DB_DeleteAction_Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON DELETE SET NULL.
        /// </summary>
        internal static string DB_DeleteAction_SetNull {
            get {
                return ResourceManager.GetString("DB_DeleteAction_SetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER .
        /// </summary>
        internal static string DB_DropTrigger {
            get {
                return ResourceManager.GetString("DB_DropTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS .
        /// </summary>
        internal static string DB_IfExists {
            get {
                return ResourceManager.GetString("DB_IfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS .
        /// </summary>
        internal static string DB_IfNotExists {
            get {
                return ResourceManager.GetString("DB_IfNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string DB_OpenParenthesis {
            get {
                return ResourceManager.GetString("DB_OpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA foreign_keys = 0;.
        /// </summary>
        internal static string DB_Pragma_ForeignKeysOff {
            get {
                return ResourceManager.GetString("DB_Pragma_ForeignKeysOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA foreign_keys = 1;.
        /// </summary>
        internal static string DB_Pragma_ForeignKeysOn {
            get {
                return ResourceManager.GetString("DB_Pragma_ForeignKeysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA table_info.
        /// </summary>
        internal static string DB_Pragma_TableInfo {
            get {
                return ResourceManager.GetString("DB_Pragma_TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCES.
        /// </summary>
        internal static string DB_References {
            get {
                return ResourceManager.GetString("DB_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string DB_Semicolon {
            get {
                return ResourceManager.GetString("DB_Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sql FROM sqlite_master WHERE type=&apos;index&apos; AND sql IS NOT NULL AND tbl_name=&apos;{0}&apos;;.
        /// </summary>
        internal static string DB_SqliteMaster_Index {
            get {
                return ResourceManager.GetString("DB_SqliteMaster_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sql FROM sqlite_master WHERE type=&apos;table&apos; AND name=&apos;{0}&apos;;.
        /// </summary>
        internal static string DB_SqliteMaster_Table {
            get {
                return ResourceManager.GetString("DB_SqliteMaster_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sql FROM sqlite_master WHERE type=&apos;trigger&apos; AND sql IS NOT NULL AND tbl_name=&apos;{0}&apos;;.
        /// </summary>
        internal static string DB_SqliteMaster_Trigger {
            get {
                return ResourceManager.GetString("DB_SqliteMaster_Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string DB_TableName_Roles {
            get {
                return ResourceManager.GetString("DB_TableName_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string DB_TableName_Users {
            get {
                return ResourceManager.GetString("DB_TableName_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AFTER UPDATE OF .
        /// </summary>
        internal static string DB_Trigger_AfterUpdate {
            get {
                return ResourceManager.GetString("DB_Trigger_AfterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DateModifiedTrigger.
        /// </summary>
        internal static string DB_Trigger_DateModified {
            get {
                return ResourceManager.GetString("DB_Trigger_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _InsertTrigger.
        /// </summary>
        internal static string DB_Trigger_Insert {
            get {
                return ResourceManager.GetString("DB_Trigger_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ON {0}
        ///      FOR EACH ROW
        ///BEGIN
        ///UPDATE {0}
        ///   SET DateModified = (strftime(&apos;%Y-%m-%d %H:%M:%f&apos;, &apos;now&apos;) )
        /// WHERE Id = NEW.Id;
        ///END;.
        /// </summary>
        internal static string DB_Trigger_UpdateStatement {
            get {
                return ResourceManager.GetString("DB_Trigger_UpdateStatement", resourceCulture);
            }
        }
    }
}
